version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    restart: always
    networks:
      - rag-net

  backend:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    container_name: flask_backend
    ports:
      - "5001:5001"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - qdrant
    networks:
      - rag-net

  frontend:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - rag-net

networks:
  rag-net:
    driver: bridge
