services:
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/Shesh009/RAG-ChatBot
    plan: free
    dockerfilePath: ./Frontend/Dockerfile
    buildFilter:
      paths:
        - Frontend/**
    startCommand: streamlit run app.py --server.port 8501
    envVars:
      - key: BACKEND_URL
        value: http://flask_backend:5001

  - type: web
    name: backend
    env: docker
    repo: https://github.com/Shesh009/RAG-ChatBot
    plan: free
    dockerfilePath: ./Backend/Dockerfile
    buildFilter:
      paths:
        - Backend/**
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: QDRANT_URL
        value: http://qdrant:6333

  - type: image
    name: qdrant
    env: docker
    repo: https://github.com/Shesh009/RAG-ChatBot
    plan: free
    dockerfilePath: ""
    image: qdrant/qdrant
    startCommand: ""
