services:
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/Shesh009/RAG-ChatBot
    plan: free
    dockerfilePath: ./Frontend/Dockerfile
    buildFilter:
      paths:
        - Frontend/**
    envVars:
      - key: BACKEND_URL
        value: http://backend:5001

  - type: web
    name: backend
    env: docker
    repo: https://github.com/Shesh009/RAG-ChatBot
    plan: free
    dockerfilePath: ./Backend/Dockerfile
    buildFilter:
      paths:
        - Backend/**
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: QDRANT_URL
        value: http://qdrant:6333

  - type: pserv
    name: qdrant
    env: docker
    repo: https://github.com/Shesh009/RAG-ChatBot
    plan: free
    dockerfilePath: ./qdrant/Dockerfile
